In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [2]:
data1 = pd.read_json('echonest-metrics.json')

In [3]:
data2 = pd.read_csv('fma-rock-vs-hiphop.csv')

In [4]:
data2.head()

track_id  bit_rate  comments        composer         date_created  \
0       135    256000         1             NaN  2008-11-26 01:43:26   
1       136    256000         1             NaN  2008-11-26 01:43:35   
2       151    192000         0             NaN  2008-11-26 01:44:55   
3       152    192000         0             NaN  2008-11-26 01:44:58   
4       153    256000         0  Arc and Sender  2008-11-26 01:45:00   

         date_recorded  duration  favorites genre_top    genres  ...  \
0  2008-11-26 00:00:00       837          0      Rock  [45, 58]  ...   
1  2008-11-26 00:00:00       509          0      Rock  [45, 58]  ...   
2                  NaN       192          0      Rock      [25]  ...   
3                  NaN       193          0      Rock      [25]  ...   
4  2008-11-26 00:00:00       405          5      Rock      [26]  ...   

  information interest  language_code  \
0         NaN     2484             en   
1         NaN     1948             en   
2         NaN      701             en   
3         NaN      637             en   
4         NaN      354             en   

                                             license listens  lyricist number  \
0  Attribution-NonCommercial-ShareAlike 3.0 Inter...    1832       NaN      0   
1  Attribution-NonCommercial-ShareAlike 3.0 Inter...    1498       NaN      0   
2  Attribution-NonCommercial-ShareAlike 3.0 Inter...     148       NaN      4   
3  Attribution-NonCommercial-ShareAlike 3.0 Inter...      98       NaN     11   
4  Attribution-NonCommercial-NoDerivatives (aka M...     424       NaN      2   

   publisher tags                       title  
0        NaN   []                Father's Day  
1        NaN   []  Peel Back The Mountain Sky  
2        NaN   []                 Untitled 04  
3        NaN   []                 Untitled 11  
4        NaN   []          Hundred-Year Flood  

[5 rows x 21 columns]

In [5]:
# from above we can take genre top and merge to previous data
data = data1.merge(data2[['genre_top', 'track_id']], on='track_id')

In [6]:
data.head()

track_id  acousticness  danceability    energy  instrumentalness  liveness  \
0         2      0.416675      0.675894  0.634476          0.010628  0.177647   
1         3      0.374408      0.528643  0.817461          0.001851  0.105880   
2         5      0.043567      0.745566  0.701470          0.000697  0.373143   
3       134      0.452217      0.513238  0.560410          0.019443  0.096567   
4       153      0.988306      0.255661  0.979774          0.973006  0.121342   

   speechiness    tempo   valence genre_top  
0     0.159310  165.922  0.576661   Hip-Hop  
1     0.461818  126.957  0.269240   Hip-Hop  
2     0.124595  100.260  0.621661   Hip-Hop  
3     0.525519  114.290  0.894072   Hip-Hop  
4     0.051740   90.241  0.034018      Rock

In [7]:
# Checking the co-relation to remove non-important labels
data.corr(numeric_only= True)

track_id  acousticness  danceability    energy  \
track_id          1.000000     -0.372282      0.049454  0.140703   
acousticness     -0.372282      1.000000     -0.028954 -0.281619   
danceability      0.049454     -0.028954      1.000000 -0.242032   
energy            0.140703     -0.281619     -0.242032  1.000000   
instrumentalness -0.275623      0.194780     -0.255217  0.028238   
liveness          0.048231     -0.019991     -0.106584  0.113331   
speechiness      -0.026995      0.072204      0.276206 -0.109983   
tempo            -0.025392     -0.026310     -0.242089  0.195227   
valence           0.010070     -0.013841      0.473165  0.038603   

                  instrumentalness  liveness  speechiness     tempo   valence  
track_id                 -0.275623  0.048231    -0.026995 -0.025392  0.010070  
acousticness              0.194780 -0.019991     0.072204 -0.026310 -0.013841  
danceability             -0.255217 -0.106584     0.276206 -0.242089  0.473165  
energy                    0.028238  0.113331    -0.109983  0.195227  0.038603  
instrumentalness          1.000000 -0.091022    -0.366762  0.022215 -0.219967  
liveness                 -0.091022  1.000000     0.041173  0.002732 -0.045093  
speechiness              -0.366762  0.041173     1.000000  0.008241  0.149894  
tempo                     0.022215  0.002732     0.008241  1.000000  0.052221  
valence                  -0.219967 -0.045093     0.149894  0.052221  1.000000

In [8]:
#track_id is not relating with any data so drop
data.drop('track_id', axis =1, inplace=True)

In [9]:
data.head()

acousticness  danceability    energy  instrumentalness  liveness  \
0      0.416675      0.675894  0.634476          0.010628  0.177647   
1      0.374408      0.528643  0.817461          0.001851  0.105880   
2      0.043567      0.745566  0.701470          0.000697  0.373143   
3      0.452217      0.513238  0.560410          0.019443  0.096567   
4      0.988306      0.255661  0.979774          0.973006  0.121342   

   speechiness    tempo   valence genre_top  
0     0.159310  165.922  0.576661   Hip-Hop  
1     0.461818  126.957  0.269240   Hip-Hop  
2     0.124595  100.260  0.621661   Hip-Hop  
3     0.525519  114.290  0.894072   Hip-Hop  
4     0.051740   90.241  0.034018      Rock

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4802 entries, 0 to 4801
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   acousticness      4802 non-null   float64
 1   danceability      4802 non-null   float64
 2   energy            4802 non-null   float64
 3   instrumentalness  4802 non-null   float64
 4   liveness          4802 non-null   float64
 5   speechiness       4802 non-null   float64
 6   tempo             4802 non-null   float64
 7   valence           4802 non-null   float64
 8   genre_top         4802 non-null   object 
dtypes: float64(8), object(1)
memory usage: 337.8+ KB


In [11]:
data.describe()

acousticness  danceability       energy  instrumentalness     liveness  \
count  4.802000e+03   4802.000000  4802.000000       4802.000000  4802.000000   
mean   4.870600e-01      0.436556     0.625126          0.604096     0.187997   
std    3.681396e-01      0.183502     0.244051          0.376487     0.150562   
min    9.491000e-07      0.051307     0.000279          0.000000     0.025297   
25%    8.351236e-02      0.296047     0.450757          0.164972     0.104052   
50%    5.156888e-01      0.419447     0.648374          0.808752     0.123080   
75%    8.555765e-01      0.565339     0.837016          0.915472     0.215151   
max    9.957965e-01      0.961871     0.999768          0.993134     0.971392   

       speechiness        tempo      valence  
count  4802.000000  4802.000000  4802.000000  
mean      0.104877   126.687944     0.453413  
std       0.145934    34.002473     0.266632  
min       0.023234    29.093000     0.014392  
25%       0.036897    98.000750     0.224617  
50%       0.049594   124.625500     0.446240  
75%       0.088290   151.450000     0.666914  
max       0.966177   250.059000     0.983649

In [12]:
data.isnull().sum()

acousticness        0
danceability        0
energy              0
instrumentalness    0
liveness            0
speechiness         0
tempo               0
valence             0
genre_top           0
dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = data.drop('genre_top', axis =1)
y = data['genre_top']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
#Giving 20% of data for testing and rest for training

In [16]:
# Using Deision trees for classification
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree = DecisionTreeClassifier()

In [18]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [19]:
predictions = dtree.predict(X_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

[[133  52]
 [ 55 721]]


              precision    recall  f1-score   support

     Hip-Hop       0.71      0.72      0.71       185
        Rock       0.93      0.93      0.93       776

    accuracy                           0.89       961
   macro avg       0.82      0.82      0.82       961
weighted avg       0.89      0.89      0.89       961



In [22]:
#using random forest for more accuracy
from sklearn.ensemble import RandomForestClassifier

In [23]:
rfc = RandomForestClassifier(n_estimators=20)

In [24]:
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20)

In [25]:
rfc_pred = rfc.predict(X_test)

In [26]:
print(confusion_matrix(y_test, rfc_pred))
print('\n')
print(classification_report(y_test, rfc_pred))

[[145  40]
 [ 32 744]]


              precision    recall  f1-score   support

     Hip-Hop       0.82      0.78      0.80       185
        Rock       0.95      0.96      0.95       776

    accuracy                           0.93       961
   macro avg       0.88      0.87      0.88       961
weighted avg       0.92      0.93      0.92       961



In [28]:
# Random Forest fetch better result than decision trees here

In [29]:
#Now , let us logistic regression
from sklearn.linear_model import LogisticRegression

In [30]:
logmodel = LogisticRegression()

In [31]:
logmodel.fit(X_train, y_train)

C:\Users\somya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
predictions = logmodel.predict(X_test)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix

In [35]:
print(confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

[[113  72]
 [ 20 756]]


              precision    recall  f1-score   support

     Hip-Hop       0.85      0.61      0.71       185
        Rock       0.91      0.97      0.94       776

    accuracy                           0.90       961
   macro avg       0.88      0.79      0.83       961
weighted avg       0.90      0.90      0.90       961



In [ ]:
# So in this exaple we can see that logistic regression is fetching the best results.